title: ALICE O2 simulation documentation
description: ALICE O2 Simulation documentation project

theme: null

debug:
  compress: false
  dist: false
  shortcodes: true

readme_index:
  with_frontmatter: true

plugins:
  - jemoji
  - jekyll-avatar
  - jekyll-mentions

exclude:
  - LICENSE
