services:
    jekyll:
       build:
          context: .
          dockerfile: dockerfile
       command: jekyll serve --watch --incremental
       ports:
          - 4000:4000
       volumes:
          - .:/srv/jekyll